title: DINO Demonstrator for NEMO 5.0.1
url: https://katavouta.github.io/our_page2/docs/assets/graphics.004.jpeg
description: "Demonstrator for the DINO configuration. A diabatic version of Neverworld2 implemented in NEMO version 5.0.1"
author: "David Kamm"

theme: minima
